server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/babytun?serverTimezone=UTC
    username: root
    password: 980214
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html; charset=utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.itlaoqi.babytun.entity

